name: mocavis-be

services:
  mocavis-be-database:
    container_name: mocavis-postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./docker/volumes/:/var/lib/postgresql/data
    networks:
      - mocavis-network

  mocavis-be-redis:
    image: redis:latest
    container_name: mocavis-redis
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - ${REDIS_PORT}
    restart: always
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
    networks:
      - mocavis-network

  mocavis-rstp:
    image: livekit/livekit-server:latest
    container_name: mocavis-livekit-server
    ports:
      - "${LIVEKIT_PORT}:7880"
      - "${LIVEKIT_TCP_PORT}:7881/tcp"
      - "${LIVEKIT_UDP_PORT}:7882/udp"
    command: --config /etc/livekit.yaml
    restart: always
    environment:
      - LIVEKIT_KEYS=${LIVEKIT_KEYS}
      - LIVEKIT_RTC_NODE_IP=${LIVEKIT_NODE_IP}
    volumes:
      - ./livekit-conf/livekit.yaml:/etc/livekit.yaml

volumes:
  postgres:

networks:
  mocavis-network:
    driver: bridge