name: Build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  be-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd web-backend
      - run: bun install
      - run: bun generate
      - run: bun lint
      - run: bun build:binary