export const ViolenceDetectionConfig = {
  USE_GLOBAL_VIOLENCE_THRESHOLD: import.meta.env.VITE_USE_GLOBAL_VIOLENCE_THRESHOLD === 'true',
  VIOLENCE_GLOBAL_CONFIDENCE_THRESHOLD: Number(
    import.meta.env.VITE_VIOLENCE_GLOBAL_CONFIDENCE_THRESHOLD || 0.5
  ),

  VIOLENCE_ASSAULT_CONFIDENCE_THRESHOLD: Number(
    import.meta.env.VITE_VIOLENCE_ASSAULT_CONFIDENCE_THRESHOLD || 0.5
  ),
  VIOLENCE_FIGHTING_CONFIDENCE_THRESHOLD: Number(
    import.meta.env.VITE_VIOLENCE_FIGHTING_CONFIDENCE_THRESHOLD || 0.5
  ),
  VIOLENCE_ROBBERY_CONFIDENCE_THRESHOLD: Number(
    import.meta.env.VITE_VIOLENCE_ROBBERY_CONFIDENCE_THRESHOLD || 0.5
  ),
  VIOLENCE_SHOOTING_CONFIDENCE_THRESHOLD: Number(
    import.meta.env.VITE_VIOLENCE_SHOOTING_CONFIDENCE_THRESHOLD || 0.5
  ),
};
