export const USE_GLOBAL_VIOLENCE_THRESHOLD = false;
export const VIOLENCE_GLOBAL_CONFIDENCE_THRESHOLD = 0.65;

export const VIOLENCE_ASSAULT_CONFIDENCE_THRESHOLD = 0.5;
export const VIOLENCE_FIGHTING_CONFIDENCE_THRESHOLD = 0.5;
export const VIOLENCE_ROBBERY_CONFIDENCE_THRESHOLD = 0.75;
export const VIOLENCE_SHOOTING_CONFIDENCE_THRESHOLD = 0.7;
