[Unit]
Description=MOCA-Vision Edge Code Service
After=network.target

[Service]
# Run as your default user
User=mendel

# Make sure this path is directed toward the edge code folder
WorkingDirectory=/mnt/sdcard/Tugas-Akhir_MonoRepo/python-code/edge

# This one needs to be directed toward the python file on your new uv venv
ExecStart=/mnt/sdcard/Tugas-Akhir_MonoRepo/python-code/edge/.venv/bin/python ./edge-code/app.py

Restart=always
RestartSec=10

Environment="PYTHONUNBUFFERED=1"

[Install]
WantedBy=multi-user.target