name: mocavis-edge-code

services:
  mocavis-edge-code:
    container_name: mocavis-edge
    image: afif1731/moca-vision-edge-code:alpha-latest
    network_mode: host
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/moca-edge-code:/app/edge-code

volumes:
  mocavis: